version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-all:
        patterns:
        - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"
    groups:
      k8s:
        patterns:
        - "k8s.io/*"
        - "sigs.k8s.io/*"

  - package-ecosystem: docker
    directory: /pkg/util/nethealth
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /test
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"
    groups:
      k8s:
        patterns:
        - "k8s.io/*"
        - "sigs.k8s.io/*"

  - package-ecosystem: docker
    directory: /test/kernel_log_generator
    schedule:
      interval: weekly
