version: "2"
run:
  tests: true
#  build-tags:
#    - journald
linters:
  default: none
  enable:
    - ineffassign
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
    goimports:
      local-prefixes:
        - k8s.io/node-problem-detector
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
