name: golangci-lint
on: [pull_request, workflow_dispatch]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24
      - name: golangci-lint
        run: make lint
