name: tag-release

on:
  push:
    branches:
      - master
    paths:
      - version.txt

permissions:
  contents: read

jobs:
  tag:
    if: ${{ github.repository == 'kubernetes/node-problem-detector' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - run: /usr/bin/git config --global user.email actions@github.com
      - run: /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
      - run: hack/tag-release.sh
        id: tag_release
    outputs:
      release_tag: ${{ steps.tag_release.outputs.release_tag }}
